spring.application.name=AquaMate

# Server
server.port=8080

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Thymeleaf (disable cache in dev)
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Jackson: JSON null 필드 제외 출력
spring.jackson.default-property-inclusion=non_null
